### ISSUE TITLE
hilbert_transform for input 

### ISSUE THREAD

**Issue by trichtu** [tsb46/complex_pca#2]
I noticed there is a .conj() operator for "hilbert_transform" function after the hilbert transformation in cpca.py. May I know why to do it? Does it effect the final results on phase?

**Comment by tsb46** [comment]
Hi @trichtu. It does. Sorry that part of the code needs to be documented. In our original manuscript, we did that so the phase angles of the complex eigenvectors were easier to read - the temporal evolution of the complex eigenvector (as reflected in the phase angles) read from left (-pi) to right (pi) - i.e. moving from -pi to pi went forward in time. On a circle, they would clockwise. Without the conjugate operation they would read right (pi) to left (-pi) (counter-clockwise on a circle). 

However, this was just our preference. You could achieve the same thing if you conjugated later. Directly on the complex eigenvectors, maybe? The conjugate operation simply flips or 'reflects' the complex number across the real -axis (x-axis).

**Comment by trichtu** [comment]
great, thanks a lot.
